version: '2'

services:

  mysql:
    image: mysql:5.7
    container_name: ${COMPANY_NAME}-${PROJECT_NAME}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${VOLUME_ROOT_PATH}/${COMPANY_NAME}/${PROJECT_NAME}/mysql:/var/lib/mysql
      - .docker/conf/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

  adminer:
    image: clue/adminer
    container_name: ${COMPANY_NAME}-${PROJECT_NAME}-adminer
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_ADMINER}
    depends_on:
      - mysql

  php:
    image: ${COMPANY_NAME}-${PROJECT_NAME}/php:${PHP_VERSION}-fpm
    container_name: ${COMPANY_NAME}-${PROJECT_NAME}-php
    build:
      context: .docker/build/php
      dockerfile: Dockerfile-${PHP_VERSION}
    volumes:
      - ./:/var/www/html
      - ${VOLUME_ROOT_PATH}/${COMPANY_NAME}/${PROJECT_NAME}/composer:/root/.composer
    depends_on:
      - mysql

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${COMPANY_NAME}-${PROJECT_NAME}-nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_NGINX}
      - PHP_CONTAINER_NAME=${COMPANY_NAME}-${PROJECT_NAME}-php
      - SYMFONY_ENTRYPOINT=${SYMFONY_ENTRYPOINT}
    volumes_from:
      - php
    volumes:
      - .docker/conf/nginx/vhost_symfony.conf.template:/etc/nginx/vhost_symfony.conf.template
      - .docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    command: /bin/bash -c "envsubst '$$PHP_CONTAINER_NAME $$SYMFONY_ENTRYPOINT' < /etc/nginx/vhost_symfony.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:

  default:
    external:
      name: ${NETWORK_NAME}
