ovski_language:
    resource: "@OvskiLanguageBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

ovski_website:
    resource: "@OvskiWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|fr|

ovski_user:
    resource: "@OvskiUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    requirements:
        _locale: en|fr

api_login_check:
    path: /api/login_check

ovski_api_language_languages:
    type:     rest
    resource: "@OvskiLanguageBundle/Controller/Api"
    prefix:   /{_locale}/api
