ovski_language:
    resource: "@OvskiLanguageBundle/Controller/"
    type:     annotation
    prefix:   /

ovski_user:
    resource: "@OvskiUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"