security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/[a-z]{2}/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider:      fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:    fos_user_security_login
                check_path:    fos_user_security_check
                default_target_path: learning
            logout:
                path:   fos_user_security_logout
                target: home
            anonymous: true

    access_control:
        - { path: "^/[a-z]{2}/api",                                        role: ROLE_USER }
        - { path: "/revision|edition|languages|edit|delete|settings|star", role: ROLE_USER }
