services:
# custom classes
    ovski.translation_manager:
        class: 'Ovski\LanguageBundle\Service\TranslationManager'
        arguments: ['@doctrine.orm.entity_manager']
# validators
    ovski.translation_requires_articles_validator:
        class: 'Ovski\LanguageBundle\Validator\Constraints\TranslationRequiresArticlesValidator'
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: translation_requires_articles_validator }
    ovski.translation_unique_validator:
        class: 'Ovski\LanguageBundle\Validator\Constraints\TranslationUniqueValidator'
        arguments: ['@doctrine.orm.entity_manager', '@security.context']
        tags:
            - { name: validator.constraint_validator, alias: translation_unique_validator }
    ovski.learning_unique_validator:
        class: 'Ovski\LanguageBundle\Validator\Constraints\LearningUniqueValidator'
        arguments: ['@doctrine.orm.entity_manager', '@security.context']
        tags:
            - { name: validator.constraint_validator, alias: learning_unique_validator }
    ovski.learning_languages_not_identical_validator:
        class: 'Ovski\LanguageBundle\Validator\Constraints\LearningLanguagesNotIdenticalValidator'
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: learning_languages_not_identical_validator }